### ISSUE TITLE
奇怪的NoSuchElementException

### ISSUE THREAD

**Issue by songjinghe** [songjinghe/temporal-storage#2]
这个问题是在解决 #1 的时候发现的。测试代码：
```java
    @Test
    public void test2fail2() throws Throwable {
        StoreBuilder stBuilder = new StoreBuilder(dbDir, true);
        store = stBuilder.store();
        for(long entityId=1; entityId<5; entityId++){
            for(int proId=0; proId<Integer.MAX_VALUE/1000-6; proId+=5){
                StoreBuilder.setIntProperty(store, 0, entityId, proId, 0); // time为0
            }
            for(int proId=0; proId<Integer.MAX_VALUE/1000-6; proId+=3){
                StoreBuilder.setIntProperty(store, 10, entityId, proId, 10); // time为10
            }
            log.debug("version {} write finish", entityId);
        }
        Slice val = store.getPointValue(1, 3, 4); //1为entityid，3为proId，4为time
        log.debug("{}", val.getInt(0));
    }
```
错误信息：
```
java.util.NoSuchElementException
	at java.util.TreeMap.key(TreeMap.java:1327)
	at java.util.TreeMap.lastKey(TreeMap.java:297)
	at org.act.temporalProperty.impl.StableLevel.getPointValue(StableLevel.java:203)
	at org.act.temporalProperty.impl.TemporalPropertyStoreImpl.getPointValue(TemporalPropertyStoreImpl.java:167)
	at org.act.temporalProperty.impl.query.range.FloorQueryTest.test2fail2(FloorQueryTest.java:46)
```
存储文件夹里只有`000001.un`、`000001.buf`和两个meta文件

**Comment by songjinghe** [comment]
如果把查询的proid换成0就没问题~但是很奇怪3也应该有啊？

**Comment by songjinghe** [comment]
目前这种测试不能再运行了，因为不能如此大批量的建立属性（每建立一个属性就要新建一个文件夹，还有相应的内存结构。。。）不晓得要多大的开销。

**Comment by songjinghe** [comment]
改了代码后运行，没有这个问题了，不过成功发现了一个未知的问题。并且解决了
